{
 "title": "ZTC Internal Metrics",
 "description": "ZTC Internal Metrics - Monitor Z telemetry data using spanmetrics connector. Focuses on CICS, DB2, MQ, and IMS subsystems.",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "sysplex",
    "label": "SYSPLEX",
    "query": {
     "query": "label_values(traces_span_metrics_calls_total, zos_sysplex_name)"
    }
   },
   {
    "name": "lpar",
    "label": "LPAR",
    "query": {
     "query": "label_values(traces_span_metrics_calls_total{zos_sysplex_name=~\"$sysplex\"}, mainframe_lpar_name)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(traces_span_metrics_calls_total{zos_sysplex_name=~\"$sysplex\", mainframe_lpar_name=~\"$lpar\"}, service_name)"
    }
   },
   { "name": "subsystem", "label": "Subsystem Type", "query": "CICS,DB2,IMS,MQ,All" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active SYSPLEX ",
   "type": "stat",
   "description": "Active SYSPLEX and LPAR count",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (zos_sysplex_name) (traces_span_metrics_calls_total{zos_sysplex_name=~\"$sysplex\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active LPAR",
   "type": "stat",
   "description": "Active LPAR count",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (mainframe_lpar_name) (traces_span_metrics_calls_total{zos_sysplex_name=~\"$sysplex\", mainframe_lpar_name=~\"$lpar\", service_name=~\"$service\"}))",
     "legendFormat": "All Subsystems"
    }
   ]
  },
  {
   "title": "Active Services",
   "type": "stat",
   "description": "Active services",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (service_name) (traces_span_metrics_calls_total{zos_sysplex_name=~\"$sysplex\", mainframe_lpar_name=~\"$lpar\", service_name=~\"$service\"}))",
     "legendFormat": "All Subsystems"
    }
   ]
  },
  { "title": "Volume Analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Current Span Rate (Gauge)",
   "type": "gauge",
   "description": "Current span rate across all selected subsystems",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "spans/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(traces_span_metrics_calls_total{zos_sysplex_name=~\"$sysplex\", mainframe_lpar_name=~\"$lpar\", service_name=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Total Span Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(traces_span_metrics_calls_total{zos_sysplex_name=~\"$sysplex\", mainframe_lpar_name=~\"$lpar\", service_name=~\"$service\"}[5m]))",
     "legendFormat": "Total Span Rate"
    }
   ]
  },
  {
   "title": "Span Rate by LPAR",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "spans/s" } },
   "targets": [
    {
     "expr": "sum by (mainframe_lpar_name) (rate(traces_span_metrics_calls_total{zos_sysplex_name=~\"$sysplex\", mainframe_lpar_name=~\"$lpar\", service_name=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "{{mainframe_lpar_name}}"
    },
    {
     "expr": "avg_over_time(sum by (mainframe_lpar_name)(rate(traces_span_metrics_calls_total{zos_sysplex_name=~\"$sysplex\", mainframe_lpar_name=~\"$lpar\", service_name=~\"$service\"}[$__rate_interval]))[1m:])",
     "legendFormat": "Current Trend {{mainframe_lpar_name}}"
    },
    {
     "expr": "avg_over_time(sum by (mainframe_lpar_name) (rate(traces_span_metrics_calls_total{zos_sysplex_name=~\"$sysplex\", mainframe_lpar_name=~\"$lpar\", service_name=~\"$service\"}[$__rate_interval]))[1w:])",
     "legendFormat": "1 Week Trend {{mainframe_lpar_name}}"
    },
    {
     "expr": "sum by (mainframe_lpar_name) (rate(traces_span_metrics_calls_total{zos_sysplex_name=~\"$sysplex\", mainframe_lpar_name=~\"$lpar\", service_name=~\"$service\"}[$__rate_interval] offset 2d))",
     "legendFormat": "Last Week {{mainframe_lpar_name}}"
    }
   ]
  },
  {
   "title": "Span Rate by Sysplex",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "spans/s" } },
   "targets": [
    {
     "expr": "sum by (zos_sysplex_name) (rate(traces_span_metrics_calls_total{zos_sysplex_name=~\"$sysplex\", mainframe_lpar_name=~\"$lpar\", service_name=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "{{zos_sysplex_name}}"
    },
    {
     "expr": "avg_over_time(sum by (zos_sysplex_name)(rate(traces_span_metrics_calls_total{zos_sysplex_name=~\"$sysplex\", mainframe_lpar_name=~\"$lpar\", service_name=~\"$service\"}[$__rate_interval]))[1m:])",
     "legendFormat": "Current Trend {{zos_sysplex_name}}"
    },
    {
     "expr": "avg_over_time(sum by (zos_sysplex_name) (rate(traces_span_metrics_calls_total{zos_sysplex_name=~\"$sysplex\", mainframe_lpar_name=~\"$lpar\", service_name=~\"$service\"}[$__rate_interval]))[1w:])",
     "legendFormat": "1 Week Trend {{zos_sysplex_name}}"
    },
    {
     "expr": "sum by (zos_sysplex_name) (rate(traces_span_metrics_calls_total{zos_sysplex_name=~\"$sysplex\", mainframe_lpar_name=~\"$lpar\", service_name=~\"$service\"}[$__rate_interval] offset 2d))",
     "legendFormat": "Last Week {{zos_sysplex_name}}"
    }
   ]
  },
  {
   "title": "Span Rate by Subsystem",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "spans/s" } },
   "targets": [
    {
     "expr": "sum(rate(traces_span_metrics_calls_total{tps_system=\"cics\", zos_sysplex_name=~\"$sysplex\", mainframe_lpar_name=~\"$lpar\", service_name=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "CICS"
    },
    {
     "expr": "sum(rate(traces_span_metrics_calls_total{db_system_name=\"ibm.db2\", zos_sysplex_name=~\"$sysplex\", mainframe_lpar_name=~\"$lpar\", service_name=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "DB2"
    },
    {
     "expr": "sum(rate(traces_span_metrics_calls_total{messaging_system=\"ibmmq\", zos_sysplex_name=~\"$sysplex\", mainframe_lpar_name=~\"$lpar\", service_name=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "MQ"
    },
    {
     "expr": "sum(rate(traces_span_metrics_calls_total{ibm_ims_processing_ims!=\"\", zos_sysplex_name=~\"$sysplex\", mainframe_lpar_name=~\"$lpar\", service_name=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "IMS"
    },
    {
     "expr": "sum(rate(traces_span_metrics_calls_total{tps_system=\"cics\", zos_sysplex_name=~\"$sysplex\", mainframe_lpar_name=~\"$lpar\", service_name=~\"$service\"}[$__rate_interval] offset 1w))",
     "legendFormat": "Last Week CICS"
    },
    {
     "expr": "sum(rate(traces_span_metrics_calls_total{db_system_name=\"ibm.db2\", zos_sysplex_name=~\"$sysplex\", mainframe_lpar_name=~\"$lpar\", service_name=~\"$service\"}[$__rate_interval] offset 1w))",
     "legendFormat": "Last Week DB2"
    },
    {
     "expr": "sum(rate(traces_span_metrics_calls_total{messaging_system=\"ibmmq\", zos_sysplex_name=~\"$sysplex\", mainframe_lpar_name=~\"$lpar\", service_name=~\"$service\"}[$__rate_interval] offset 1w))",
     "legendFormat": "Last Week MQ"
    },
    {
     "expr": "sum(rate(traces_span_metrics_calls_total{ibm_ims_processing_ims!=\"\", zos_sysplex_name=~\"$sysplex\", mainframe_lpar_name=~\"$lpar\", service_name=~\"$service\"}[$__rate_interval] offset 1w))",
     "legendFormat": "Last Week IMS"
    },
    {
     "expr": "sum(rate(traces_span_metrics_calls_total{tps_system=\"cics\", zos_sysplex_name=~\"$sysplex\", mainframe_lpar_name=~\"$lpar\", service_name=~\"$service\"}[$__rate_interval] offset 30d))",
     "legendFormat": "Last Month CICS"
    },
    {
     "expr": "sum(rate(traces_span_metrics_calls_total{db_system_name=\"ibm.db2\", zos_sysplex_name=~\"$sysplex\", mainframe_lpar_name=~\"$lpar\", service_name=~\"$service\"}[$__rate_interval] offset 30d))",
     "legendFormat": "Last Month DB2"
    },
    {
     "expr": "sum(rate(traces_span_metrics_calls_total{messaging_system=\"ibmmq\", zos_sysplex_name=~\"$sysplex\", mainframe_lpar_name=~\"$lpar\", service_name=~\"$service\"}[$__rate_interval] offset 30d))",
     "legendFormat": "Last Month MQ"
    },
    {
     "expr": "sum(rate(traces_span_metrics_calls_total{ibm_ims_processing_ims!=\"\", zos_sysplex_name=~\"$sysplex\", mainframe_lpar_name=~\"$lpar\", service_name=~\"$service\"}[$__rate_interval] offset 30d))",
     "legendFormat": "Last Month IMS"
    }
   ]
  },
  {
   "title": "Span Rate by Services",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "spans/s" } },
   "targets": [
    {
     "expr": "sum by (service_name) (\n  rate(traces_span_metrics_calls_total{\n    zos_sysplex_name=~\"$sysplex\",\n    mainframe_lpar_name=~\"$lpar\",\n    service_name=~\"$service\"\n  }[$__rate_interval])\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (service_name) (\n  rate(traces_span_metrics_calls_total{\n    zos_sysplex_name=~\"$sysplex\",\n    mainframe_lpar_name=~\"$lpar\",\n    service_name=~\"$service\"\n  }[$__rate_interval] offset 1w)\n)",
     "legendFormat": "Last Week {{service_name}}"
    },
    {
     "expr": "sum by (service_name) (\n  rate(traces_span_metrics_calls_total{\n    zos_sysplex_name=~\"$sysplex\",\n    mainframe_lpar_name=~\"$lpar\",\n    service_name=~\"$service\"\n  }[$__rate_interval] offset 30d)\n)",
     "legendFormat": "Last Month {{service_name}}"
    }
   ]
  },
  { "title": "Span Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Span Distribution by SYSPLEX",
   "type": "piechart",
   "description": "Distribution across SYSPL",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (zos_sysplex_name) (traces_span_metrics_calls_total{zos_sysplex_name=~\"$sysplex\", mainframe_lpar_name=~\"$lpar\", service_name=~\"$service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Span Distribution by LPAR",
   "type": "piechart",
   "description": "Distribution across LPARS",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (mainframe_lpar_name) (traces_span_metrics_calls_total{zos_sysplex_name=~\"$sysplex\", mainframe_lpar_name=~\"$lpar\", service_name=~\"$service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Span distribution across Subsystem",
   "type": "piechart",
   "description": "Distribution across subsystems",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(traces_span_metrics_calls_total{tps_system=\"cics\", zos_sysplex_name=~\"$sysplex\", mainframe_lpar_name=~\"$lpar\", service_name=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "CICS"
    },
    {
     "expr": "sum(rate(traces_span_metrics_calls_total{db_system_name=\"ibm.db2\", zos_sysplex_name=~\"$sysplex\", mainframe_lpar_name=~\"$lpar\", service_name=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "DB2"
    },
    {
     "expr": "sum(rate(traces_span_metrics_calls_total{messaging_system=\"ibmmq\", zos_sysplex_name=~\"$sysplex\", mainframe_lpar_name=~\"$lpar\", service_name=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "MQ"
    },
    {
     "expr": "sum(rate(traces_span_metrics_calls_total{ibm_ims_processing_ims!=\"\", zos_sysplex_name=~\"$sysplex\", mainframe_lpar_name=~\"$lpar\", service_name=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "IMS"
    }
   ]
  },
  {
   "title": "Span distribution across Services",
   "type": "piechart",
   "description": "Distribution across Services",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (service_name)(\n  rate(traces_span_metrics_calls_total{\n    zos_sysplex_name=~\"$sysplex\",\n    mainframe_lpar_name=~\"$lpar\",\n    service_name=~\"$service\"\n  }[$__rate_interval])\n)\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Current Subsystem Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "CICS Span Rate (Gauge)",
   "type": "gauge",
   "description": "CICS subsystem span rate",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "spans/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(traces_span_metrics_calls_total{tps_system=\"cics\", zos_sysplex_name=~\"$sysplex\", mainframe_lpar_name=~\"$lpar\", service_name=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "CICS"
    }
   ]
  },
  {
   "title": "DB2 Span Rate (Gauge)",
   "type": "gauge",
   "description": "DB2 subsystem span rate",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "spans/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(traces_span_metrics_calls_total{db_system_name=\"ibm.db2\", zos_sysplex_name=~\"$sysplex\", mainframe_lpar_name=~\"$lpar\", service_name=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "DB2"
    }
   ]
  },
  {
   "title": "MQ Span Rate (Gauge)",
   "type": "gauge",
   "description": "MQ subsystem span rate",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "spans/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(traces_span_metrics_calls_total{messaging_system=\"ibmmq\", zos_sysplex_name=~\"$sysplex\", mainframe_lpar_name=~\"$lpar\", service_name=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "MQ"
    }
   ]
  },
  {
   "title": "IMS Span Rate (Gauge)",
   "type": "gauge",
   "description": "IMS subsystem span rate",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "spans/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(traces_span_metrics_calls_total{ibm_ims_processing_ims!=\"\", zos_sysplex_name=~\"$sysplex\", mainframe_lpar_name=~\"$lpar\", service_name=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "IMS"
    }
   ]
  },
  {
   "title": "Error Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "collapsed": true,
   "panels": [
    {
     "title": "Error Rate % (Gauge)",
     "type": "bargauge",
     "description": "Percentage of spans with error status",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 * sum by (subsystem_type) (\n  rate(traces_span_metrics_calls_total{\n    error_type!=\"\",\n    zos_sysplex_name=~\"$sysplex\",\n    mainframe_lpar_name=~\"$lpar\",\n    service_name=~\"$service\"\n  }[$__rate_interval])\n)\n/\n sum by (subsystem_type) (\n  rate(traces_span_metrics_calls_total{\n    zos_sysplex_name=~\"$sysplex\",\n    mainframe_lpar_name=~\"$lpar\",\n    service_name=~\"$service\"\n  }[$__rate_interval])\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Error Rate Over Time",
     "type": "timeseries",
     "description": "Error rate trend over time across all subsystems",
     "gridPos": { "h": 10, "w": 18, "x": 6, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 * sum by (service_name)(rate(traces_span_metrics_calls_total{\n  error_type!=\"\",\n  zos_sysplex_name=~\"$sysplex\",\n  mainframe_lpar_name=~\"$lpar\",\n  service_name=~\"$service\"\n}[$__rate_interval]))\n/\nsum by (service_name)(rate(traces_span_metrics_calls_total{\n  zos_sysplex_name=~\"$sysplex\",\n  mainframe_lpar_name=~\"$lpar\",\n  service_name=~\"$service\"\n}[$__rate_interval]))\n",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}